spring:
  profiles:
    group:
      local:
        - local
        - local-s3
      real:
        - real
        - real-db
        - real-s3
  session:
    store-type: jdbc
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  servlet:
    multipart:
      max-file-size: 5MB
server:
  servlet:
    session:
      tracking-modes: cookie
