spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  redis:
    host: redis
    port: 6379
    username:
    password:
decorator:
  datasource:
    p6spy:
      enable-logging: false
firebase-token-path: 'file:/home/ec2-user/app/tokens/firebase-adminsdk.json'
apple-key-path: 'file:/home/ec2-user/app/tokens/apple_plango_key.p8'
