spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      local:
        - local
        - local-s3
        - local-auth
      real:
        - real
        - real-db
        - real-s3
        - real-auth
  session:
    store-type: jdbc
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: notice.plango@gmail.com
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
server:
  tomcat:
    max-http-form-post-size: 5MB
  servlet:
    session:
      tracking-modes: cookie
