spring:
  profiles:
    group:
      local:
        - local
        - local-s3
        - local-auth
      real:
        - real
        - real-db
        - real-s3
        - real-auth
  session:
    store-type: jdbc
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  servlet:
    multipart:
      max-file-size: 5MB
server:
  tomcat:
    max-http-form-post-size: 5MB
  servlet:
    session:
      tracking-modes: cookie
