spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
decorator:
  datasource:
    p6spy:
      enable-logging: false
firebase-token-path: 'file:/home/ec2-user/app/firebase/firebase-adminsdk.json'
