version: "3"

services:
  plango:
    build: /home/ec2-user/app/plango-backend/
    restart: on-failure
    volumes:
      - /home/ec2-user/app:/home/ec2-user/app
    ports:
      - "8081:8080"

networks:
  default:
    external:
      name: plango
