version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    environment:
      TZ: "Asia/Seoul"
    command: redis-server

networks:
  default:
    external:
      name: plango
