name: plango-push-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Run Gradle Test
        run: ./gradlew test
        shell: bash

      - name: Check Test Status
        run: |
          if [ ${{ job.status }} != "success" ]; then
            curl -X POST -H 'Content-type: application/json' --data '{
              "text": "Push한 코드가 테스트에 실패했습니다. 내용을 확인해주세요."
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
          fi
